# -*- coding: utf-8 -*-
"""
PLAY49 — 종목 데모 조립기 (삼성전자 · SK하이닉스).

AI 에이전트(서브에이전트)가 웹에서 수집·증류해 stocks/*.json 에 저장한
종목별 리포트(주장/근거/결론 포함)를 읽어 프론트가 먹는 data.json/data.js 로 조립한다.

- 리포트 발행일을 차트 거래일(series) 중 가장 가까운 날짜로 '스냅'해 핀 위치를 잡는다
  (series 범위 밖 리포트는 핀 없이 피드에만 노출 — 거짓 핀 안 만듦).
- 리포트마다 id 부여, curated=True 표시.

실행:  python build_stocks.py
"""
import json, os, io, glob, datetime
from datetime import date as D

HERE = os.path.dirname(os.path.abspath(__file__))
SD = os.path.join(HERE, "stocks")
ORDER = ["005930", "000660", "PLTR", "NVDA"]   # 삼성 · 하이닉스 · 팔란티어 · 엔비디아


def pd(s):
    y, m, d = map(int, s.split("-"))
    return D(y, m, d)


def nearest_in_range(dt, sdates):
    """series 범위 안이면 가장 가까운 거래일 반환, 밖이면 None."""
    if pd(dt) < pd(sdates[0]) or pd(dt) > pd(sdates[-1]):
        return None
    return min(sdates, key=lambda s: abs((pd(s) - pd(dt)).days))


def build():
    stocks = []
    for f in sorted(glob.glob(os.path.join(SD, "*.json"))):
        s = json.load(io.open(f, encoding="utf-8"))
        s["price"] = s.pop("currentPrice", s.get("price"))
        s["change"] = s.pop("changePct", s.get("change", 0))
        s["note"] = "추정 가격선(실제 일별종가 아님) · 리포트·목표가는 실제(웹 리서치)"
        sdates = [p["date"] for p in s["series"]]
        s["reports"].sort(key=lambda r: r["date"])          # 발행순
        for i, r in enumerate(s["reports"], 1):
            r["id"] = "%s_%d" % (s["ticker"], i)
            r.setdefault("curated", True)
            pin = nearest_in_range(r["date"], sdates)
            if pin:
                r["pinDate"] = pin
        stocks.append(s)

    stocks.sort(key=lambda s: ORDER.index(s["ticker"]) if s["ticker"] in ORDER else 99)

    data = {
        "stocks": stocks,
        "meta": {
            "generated_at": datetime.datetime.now().strftime("%Y-%m-%d %H:%M"),
            "source": "AI 에이전트 웹 리서치 (KB·한화·Goldman·Nomura 등)",
            "n_stocks": len(stocks),
            "no_live_api": True,
        },
    }
    payload = json.dumps(data, ensure_ascii=False, indent=2)
    io.open(os.path.join(HERE, "data.json"), "w", encoding="utf-8").write(payload + "\n")
    js = "// AUTO-GENERATED by build_stocks.py — AI 에이전트 웹 리서치 기반. 실시간 API 미사용.\n"
    js += "window.DEMO_DATA = " + payload + ";\n"
    io.open(os.path.join(HERE, "data.js"), "w", encoding="utf-8").write(js)

    print("[ok] stocks=%d" % len(stocks))
    for s in stocks:
        pinned = sum(1 for r in s["reports"] if r.get("pinDate"))
        print("   - %s %s | reports=%d (pinned=%d) | %s"
              % (s["ticker"], s["name"], len(s["reports"]), pinned, s["price"]))


if __name__ == "__main__":
    build()
